# This is an unnoficial Catppuccin theme, still a WIP, not sure what I'm doing
# Originally the default file in the helix documentation
attribute = "lilac"
keyword = "almond"
"keyword.directive" = "lilac" # -- preprocessor comments (#if in C)
namespace = "lilac"
punctuation = "lavender"
"punctuation.delimiter" = "lavender"
operator = "lilac"
special = "honey"
variable.other.member = "white"
variable = "lavender"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
"variable.parameter" = { fg = "lavender" }
"variable.builtin" = "pink"
type = "white"
"type.builtin" = "white" # TODO: distinguish?
constructor = "lilac"
function = "white"
"function.macro" = "lilac"
"function.builtin" = "white"
tag = "almond"
comment = "comet"
constant = "white"
"constant.builtin" = "white"
string = "green"
"constant.numeric" = "peach"
"constant.character.escape" = "honey"
# used for lifetimes
label = "honey"

"markup.heading" = "lilac"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = "almond"
"markup.raw" = "almond"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6f44f0"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "midnight" }
"ui.linenr" = { fg = "comet" }
"ui.linenr.selected" = { fg = "lilac" }
"ui.statusline" = { fg = "lilac", bg = "revolver" }
"ui.statusline.inactive" = { fg = "lavender", bg = "revolver" }
"ui.popup" = { bg = "revolver" }
"ui.window" = { fg = "latenight" }
"ui.help" = { bg = "#7958DC", fg = "#171452" }

"ui.text" = { fg = "lavender" }
"ui.text.focus" = { fg = "white" }

"ui.selection" = { bg = "#540099" }
"ui.selection.primary" = { bg = "#540099" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.highlight" = { bg = "latenight" }

"ui.menu.selected" = { fg = "revolver", bg = "white" }

diagnostic = { modifiers = ["underlined"] }

warning = "lightning"
error = "apricot"
info = "delta"
hint = "green"

[palette]
white = "#d9e0ee"
lilac = "#ddb6f2"
lavender = "#c9cbff"
comet = "#575268"
latenight = "#1e1e2e"
midnight = "#1e1d2f"
revolver = "#302d41"

green = "#abe9b3"
teal = "#b5e8e0"
pink = "#f5c2e7"
almond = "#eccdba"
peach = "#f8bd96"
honey = "#fae3b0"

apricot = "#f47868"
lightning = "#ffcd1c"
delta = "#6f44f0"
